<a href="https://colab.research.google.com/github/SanePai/ECE-F344-Information-theory-and-Coding-Assignment-1/blob/main/ITC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install scikit-dsp-comm

In [2]:
import sk_dsp_comm.fec_block as block
import numpy as np
import pandas as pd

In [3]:
n = int(input("Enter n: \t")) #Input the n,k values for a hamming code
k = int(input("Enter k: \t"))
parity = n-k

Enter n: 	7
Enter k: 	4


In [4]:
hh1 = block.fec_hamming(parity) #Instantiating a fec_hamming class instance(hh1)

In [5]:
print(f"n: {hh1.n} \nk: {hh1.k}\nGenerator Matrix:\n{hh1.G}") #n,k and generator matrix of the hamming code

n: 7 
k: 4
Generator Matrix:
[[1 0 0 0 1 1 1]
 [0 1 0 0 1 1 0]
 [0 0 1 0 0 1 1]
 [0 0 0 1 1 0 1]]


In [6]:
msg_len = (2**hh1.k) - 1

In [7]:
msg_array = [x for x in range(msg_len+1)]
print(f"Message array(Decimal Form): {msg_array}") #Creating a decimal message array

Message array(Decimal Form): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [8]:
def dToBi(n):
  '''Returns a fixed length binary bit array for a given message'''  
  return bin(n).replace("0b","").zfill(hh1.k) 
def tostring(aray):
  '''Converts a bit array to a string'''
  string = ''
  aray = aray.tolist()
  for i in range(len(aray)):
    string = string + str(aray[i])
  return string

In [9]:
def ham(msg):
  '''Returns a hamming encoded message for a given input message'''
  x = np.array([int(a) for a in dToBi(msg)])
  y = hh1.hamm_encoder(x)
  y = np.array([int(a) for a in y])
  return y

In [10]:
code = [] #Empty list to hold codewords 
for i in msg_array:
  code.append(ham(i))
code = np.array(np.concatenate(code, axis=0)) #Concatenate the codeword(list to string)
code.resize((2**hh1.k,hh1.n)) #Resize the codeword list
# print(code)
msg_len = (2**hh1.k)-1
Table = [] #Table of added codewords
for i in range(msg_len+1):
  for j in range(msg_len+1):
    Table.append(tostring(code[i,:]^code[j,:]))
# Table


In [11]:
code1 = [] #container to hold he original codewords in a string form
m,n = np.shape(code)
for i in range(m):
  code1.append(tostring(code[i,:]))
print(f"Codewords:\n{code1}")

Codewords:
['0000000', '0001101', '0010011', '0011110', '0100110', '0101011', '0110101', '0111000', '1000111', '1001010', '1010100', '1011001', '1100001', '1101100', '1110010', '1111111']


In [12]:
Table_grid = np.array(Table) #Array to print a table
Table_grid.resize((2**hh1.k,2**hh1.k)) # Resize the table to (2^k + 1)x(2^k + 1)

In [13]:
np.shape(Table_grid)

(16, 16)

In [14]:
Table_grid_df = pd.DataFrame(Table_grid, index = code1, columns = code1)
print("Table size: ", Table_grid_df.shape)#Shape doesnt include headers, so actual size is (17,17) for (7,4) Hamming code.
print("\nTable:")
Table_grid_df


Table size:  (16, 16)

Table:


0000000  0001101  0010011  0011110  ...  1100001  1101100  1110010  1111111
0000000  0000000  0001101  0010011  0011110  ...  1100001  1101100  1110010  1111111
0001101  0001101  0000000  0011110  0010011  ...  1101100  1100001  1111111  1110010
0010011  0010011  0011110  0000000  0001101  ...  1110010  1111111  1100001  1101100
0011110  0011110  0010011  0001101  0000000  ...  1111111  1110010  1101100  1100001
0100110  0100110  0101011  0110101  0111000  ...  1000111  1001010  1010100  1011001
0101011  0101011  0100110  0111000  0110101  ...  1001010  1000111  1011001  1010100
0110101  0110101  0111000  0100110  0101011  ...  1010100  1011001  1000111  1001010
0111000  0111000  0110101  0101011  0100110  ...  1011001  1010100  1001010  1000111
1000111  1000111  1001010  1010100  1011001  ...  0100110  0101011  0110101  0111000
1001010  1001010  1000111  1011001  1010100  ...  0101011  0100110  0111000  0110101
1010100  1010100  1011001  1000111  1001010  ...  0110101  0111000  0100110  0101011
1011001  1011001  1010100  1001010  1000111  ...  0111000  0110101  0101011  0100110
1100001  1100001  1101100  1110010  1111111  ...  0000000  0001101  0010011  0011110
1101100  1101100  1100001  1111111  1110010  ...  0001101  0000000  0011110  0010011
1110010  1110010  1111111  1100001  1101100  ...  0010011  0011110  0000000  0001101
1111111  1111111  1110010  1101100  1100001  ...  0011110  0010011  0001101  0000000

[16 rows x 16 columns]

In [15]:
# def gridprint(aray):
#   '''Custom function to print the table with clear grid lines'''
#   m,n = np.shape(aray)
#   for i in range(0,m):
#     for j in range(0,n):
#       print(aray[i][j] + '  |  ', end= '')
#     print('\n------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------') 

In [16]:
# print("Table:\n")
# gridprint(Table_grid) #Print the table

In [17]:
#Check if all elements in 'Table' are valid codewords(elements in 'code')
count = 0
bol = True
for i in range(len(Table)):
  if Table[i] in code1:
    print("Resultant codeword is valid")
  else:
    print("Not Valid")
    bol = False
if bol == True:
  print("\nAll codewords are valid.Hence proved.")

Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword is valid
Resultant codeword i